# Site settings
title: FlixShare
email: flixshare365@gmail.com
# url: https://example.github.io
description: "Share Netflix, Get Netflix for ₹225. We are a community to help people grouping. Save money today."
keywords: "Share Netflix, Get Netflix for 225"
skills: "Netflix ₹225 per month for 1 user"
meta_author: Flix Share

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EE3522 #e50913 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 181818 #2c3e50 #FD6E8A
  secondary-dark: 363636 #233140 #A2122F

# Footer settings
footer:
  copyright: 
  location: 
  social: 
  credits: Disclaimer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: This is not an official website from Netflix and we do not have any association with Netflix. We are a community to facilitate grouping of people who want to share Netflix and save money.
#'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
# Build settings
markdown: 
permalink: 
